

# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:tmB8e1MSvcprJfGbeEVxDQYDf+mozDYPgg7J18RUSf4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: booking_tourismodb
  DB_USERNAME: root
  DB_PASSWORD: 
  DB_SOCKET: "/cloudsql/tourismoph:us-central1:tourismoapp"

  ## To use Stackdriver logging in your Laravel application, copy
  ## "app/Logging/CreateStackdriverLogger.php" and "config/logging.php"
  ## into your Laravel application. Then uncomment the following line:
  # LOG_CHANNEL: stackdriver